project_id = "ffxvnhrqxkirdogknoid"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
additional_redirect_urls = ["https://127.0.0.1:3000/**"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true

[functions.clock-punch]
verify_jwt = true

[functions.time-now]
verify_jwt = false

[functions.inventory-save-credentials]
verify_jwt = true

[functions.square-test-connection]
verify_jwt = true

[functions.square-import-products]
verify_jwt = true

[functions.square-push-products]
verify_jwt = true

[functions.import-watchdog]
verify_jwt = true

[functions.import-abort]
verify_jwt = true

[functions.backfill-pos-links]
verify_jwt = true

[functions.cleanup-product-data]
verify_jwt = true

[functions.send-employee-invite]
verify_jwt = true

[functions.station-login]
verify_jwt = false

[functions.station-clock-punch]
verify_jwt = false

[functions.product-catalog-backup]
verify_jwt = true

[functions.reset-product-catalog]
verify_jwt = true

[functions.search-products]
verify_jwt = true

[functions.generate-label]
verify_jwt = true

[functions.printnode-printers]
verify_jwt = true

[functions.printnode-print]
verify_jwt = true

[functions.get-label-print-config]
verify_jwt = true

[functions.update-label-print-config]
verify_jwt = true