// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffxvnhrqxkirdogknoid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmeHZuaHJxeGtpcmRvZ2tub2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzYzNjYsImV4cCI6MjA3MTMxMjM2Nn0.1eEVGG_trNVc9qHEw4SiuaS4gu1eKkJ61pzhmVIMbtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});